# configuration to connect impala
# IMPALA_HOST: 'VHEKPGNN-VIP'
host: '10.168.49.12'
port: 21050

# query to retrieve data (multiple mcc, mnc, rat type, bound type)
query_file: './query.txt'

# columns to perform feature engineering
columns_to_engineer: ['success_count', 'fail_count']